Add type declaration for useLocalStorage
uidotdev/usehooks pull request #228
Opened 2023-09-03 08:05 UTC by jack0pan

2023-09-06 16:05 UTC, hakubo commented
Looks like useSessionStorage is also missing.

2023-09-07 21:18 UTC, mauriciabad requested changes

2023-09-07 21:18 UTC, mauriciabad commented on index.d.ts
> +  export function useLocalStorage<T>(
`T` cannot be anything here. It has to be something that `JSON.stringify` can handle, so only objects with arrays or primitives.

For example, this can't handle a `Map` or `Set` or anything like that, but TypeScript won't complain with the given code.

2023-09-08 06:35 UTC, jack0pan commented on index.d.ts
> +  export function useLocalStorage<T>(
In TypeScript, the parameter type of `JSON.stringify` is `any`, so using `T` here is also acceptable. We'll leave the type checking to the user.

https://github.com/microsoft/TypeScript/blob/eb374c28d6810e317b0c353d9b1330b0595458f4/src/lib/es5.d.ts#L1128

2023-09-08 11:10 UTC, mauriciabad approved these changes

2023-09-09 14:49 UTC, faridyusof727 approved these changes

2023-09-13 06:04 UTC, jeniabrook commented
> Looks like useSessionStorage is also missing.

@hakubo I've opened a [PR](https://github.com/uidotdev/usehooks/pull/235) for that.

2023-09-15 07:14 UTC, hakubo commented
@jeniabrook nice. Thanks.

Can we have them merged ? :)

2023-09-18 15:23 UTC, merged

2023-09-18 15:23 UTC, tylermcginnis commented
Thank you!